app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Models\Item\Category as ItemCategory;
use App\Models\Content\Category as ContentCategory;


Route::get('/auth/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('/auth/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('/auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);


Route::controllers([
    'password' => 'Auth\PasswordController',
]);


Route::group(['namespace' => 'File'], function()
{
    Route::post('files/wisiwyg_upload}',
        ['as' => 'files.wisiwyg_upload', 'uses' => 'FilesController@wisiwyg_upload']
    );

    Route::get('images/{id}/resized/{size}/{crop?}',
        ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
    );
    Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
    Route::resource('files', 'FilesController', ['except' => ['destroy']]);
});


// Admin area
Route::get('admin', function () {
    return redirect('/admin/items');
});


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function()
{
    Route::get('items/create/{category_id?}', ['as' => 'admin.items.create', 'uses' => 'ItemsController@create']);
    Route::resource('items', 'ItemsController', ['except' => ['create']]);

    Route::get('contents/create/{category_id?}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
    Route::resource('contents', 'ContentsController', ['except' => ['create']]);

    Route::resource('discounts', 'DiscountsController');

    Route::resource('calculator', 'CalculatorController', ['only' => ['index', 'update']]);
    Route::resource('menu', 'MenuController', ['only' => ['index', 'update']]);

    Route::resource('orders', 'OrderController', ['only' => ['index', 'edit', 'update']]);

    Route::resource('users', 'UsersController', ['except' => ['show']]);

    Route::resource('dynamic_attributes', 'DynamicAttributesController', ['only' => ['index', 'edit']]);
    Route::post('dynamic_attributes/save', ['as' => 'admin.dynamic_attributes.save', 'uses' => 'DynamicAttributesController@save']);

});



Route::group(['middleware' => ['cart', 'seotags']], function () {

    Route::get('/', 'WelcomeController@index');


    Route::get('items/{category_id}', [
        'as' => 'items.index',
        'uses' => 'ItemsController@index'
    ])
        ->where(['category_id' => collect(ItemCategory::ids())->implode('|')]);

    Route::resource('items', 'ItemsController', ['only' => ['show']]);


    Route::get('{category_id}', [
        'as' => 'contents.index',
        'uses' => 'ContentsController@index'
    ])
    ->where(['category_id' => collect(ContentCategory::ids())->implode('|')]);

    Route::get('{category_id}/{id}', [
        'as' => 'contents.show',
        'uses' => 'ContentsController@show'
    ])
    ->where(['category_id' => collect(ContentCategory::ids())->implode('|')]);


    Route::get('calculator', ['as' => 'calculator', 'uses' => 'CalculatorController@index']);

});

Route::resource('cart', 'CartController', ['except' => ['store']]);
Route::post('cart/buy', ['as' => 'cart.buy', 'uses' => 'CartController@buy']);
Route::post('cart/{item_id}', ['as' => 'cart.store', 'uses' => 'CartController@store']);
Route::get('cart/refresh_status', ['as' => 'cart.refresh_status', 'uses' => 'CartController@refresh_status']);

resources/views/admin/partials/breadcrumbs.blade.php
<ol class="breadcrumb">
    @foreach ($crumbs as $crumb)
        @if ( isset($crumb['active']) && $crumb['active'] )
            <li class="active">{!! $crumb['title'] !!}</li>
        @else
            <li>{!! link_to($crumb['url'], $crumb['title']) !!}</li>
        @endif
    @endforeach
</ol>

resources/views/admin/partials/errors.blade.php
@if (count($errors) > 0)
    <div class="alert alert-warning">
        Что-то <strong>не так</strong>
        с данными в вашей форме!<br><br>
        <ul>
            @foreach ($errors as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/partials/lifecycle_menu.blade.php
<div class="btn-group">

    <?php
    $state_menu = [
            'live' => 'Живые',
            'archive' => 'Архивные'
    ];

    $active_state = $state ? $state : 'live';
    ?>

    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {!! $state_menu[$active_state] !!} <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        @foreach($state_menu as $state => $state_title)
            <li>{!! link_to_route($route, $state_title, ['state' => $state ], []) !!}</li>
        @endforeach
    </ul>
</div>

resources/views/admin/partials/navbar.blade.php
<?php

use App\Order;

$new_orders_count = Order::where('state', 'not_viewed')->count();

$active = [];

$menu = [
        /*'ItemsController' => [
                'title' => 'Tовары',
                'url' => route('admin.items.index'),
        ],*/

        'dropdown'  => [
                'title' => 'Каталог',
                'subs' => [
                        'ItemsController' => [
                                'title' => 'Tовары',
                                'url'   => route('admin.items.index'),
                        ],
                        'DynamicAttributesController' => [
                                'title' => 'Найстройки',
                                'url'   => route('admin.dynamic_attributes.index'),
                        ],
                ]
        ],

        'ContentsController'  => [
                'title' => 'Контент',
                'url' => route('admin.contents.index'),
        ],
        'OrdersController'  => [
                'title' => 'Заказы',
                'url' => route('admin.orders.index'),
                'badge' => $new_orders_count,
        ],
        'CalculatorController'  => [
                'title' => 'Калькулятор',
                'url' => route('admin.calculator.index'),
        ],
        'DiscountController'  => [
                'title' => 'Скидки',
                'url' => route('admin.discounts.index'),
        ],
        'MenuController'  => [
                'title' => 'Меню',
                'url' => route('admin.menu.index'),
        ],

    /*'dropdown'  => [
        'title' => 'Настройки',
        'subs' => [
            'CalculatorController' => [
                'title' => 'Калькулятор',
                'url'   => route('admin.calculator.index'),
            ],
            'MenuController' => [
                'title' => 'Меню',
                'url'   => route('admin.menu.index'),
            ],
        ]
    ],*/
];

foreach ($menu as $item => $options)
{
    if ( $item == 'dropdown' )
    {
        $active[$item] = $item;

        foreach ($options['subs'] as $subitem => $options)
        {
            if ( $subitem == $controller )
            {
                $active[$subitem] = 'active';
                $active[$item] = 'active';
            } else {
                $active[$subitem] = '';
            }
        }

    } else {
        $active[$item] = $item == $controller ? 'active' : '';
    }
}

$active[$controller] = isset($active[$controller]) ? $active[$controller] : '';

//var_dump($active);

?>

<ul class="nav navbar-nav">


    @if (Auth::check())

        @foreach ($menu as $item => $options)

            <li class="{{ $active[$item] }}">

                @if ( $item == 'dropdown' )

                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {{ $options['title'] }}  <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        @foreach ($options['subs'] as $subitem => $options)

                            <li class="{{ $active[$subitem] }}">
                                <a href="{{ $options['url'] }}">
                                    {{ $options['title'] }}
                                </a>
                            </li>

                        @endforeach
                    </ul>

                @else
                    <a href={{ $options['url'] }}>
                        {{ $options['title'] }}

                        @if (isset($options['badge']) && $options['badge'])
                            <span class="badge">{!! $options['badge'] !!}</span>
                        @endif
                    </a>
                @endif
            </li>

        @endforeach
    @endif
</ul>

<ul class="nav navbar-nav navbar-right">
    @if (Auth::guest())
        <li>{!! link_to_route('auth.login', 'Войти') !!}</li>
    @else
        @can('watch-users')
            <li>{!! link_to_route('admin.users.index', 'Пользователи') !!}</li>
        @endcan

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-expanded="false">{{ Auth::user()->name }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li>{!! link_to_route('auth.logout', 'Выйти') !!}</li>
            </ul>
        </li>
    @endif
</ul>